language: go

addons:
  apt:
    packages:
      - asciidoc
      - libxml2-utils

matrix:
  include:
    - go: 1.7.x
    - go: 1.8.x
    - go: tip
  allow_failures:
    - go: tip

notifications:
  email: false
